name: Build Pages

on:
  push:
    paths:
      - "notes/**" # notes 디렉토리의 변경사항이 있을 때 실행
  pull_request:
    paths:
      - "notes/**"

jobs:
  build-pages:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 3. 의존성 설치
      - name: Install dependencies
        run: yarn install

      # 4. 병합 실행
      - name: Build pages
        run: yarn build:pages

      # 5. 변경사항 커밋 및 푸시
      - name: Commit and push changes
        run: |
          git config user.name "jeongchongmu"
          git add pages/**
          git commit -m "Update pages [CI]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
